### ISSUE TITLE
Finish the report for the concept phase

### ISSUE THREAD

**Issue by jmesserli** [outcobra/docs#2]
We still have a lot to do to finish the concept report for tomorrow ​:date:​. Because of that, I'd like to assign everyone some tasks to make sure we can finish the report as efficiently as possible.
- [x] copy-paste requirements :clipboard: @jmesserli
- [x] copy-paste domain model and describe entities where necessary :clipboard: @jmesserli
- [x] define services & endpoints :construction: @jmesserli
- [x] write architecture stuff :pencil2: @M4R1KU 
- [x] draw mockups and pageflow stuff :city_sunrise: @Xanthos3 
- [x] finish test specification... @needToRoll 
- [x] ...and paste it in there :white_check_mark: @jmesserli

Please acknowledge your tasks if it's ok.

**Comment by needToRoll** [comment]
All the tasks have been acknowledged and the complete file has been reviewed.
You can take a look at the submitted version [here](https://drive.google.com/file/d/0B5Y99fHfY0DfYnBSWGotRXJJdUU/view?usp=sharing)

Lets start the "realisation" @outcobra/developers 😄
